// Generates contracts/src/SeerMatrix.sol from web/lib/matrix.json and the solver's integer log-likelihood table,
// so the on-chain consistency check and the off-chain solver can never drift apart.
//   node scripts/gen-matrix-sol.ts
import { readFileSync, writeFileSync } from "node:fs";
import { keccak256, toBytes } from "viem";
import { FIT_FORFEIT, FIT_FULL, JOBS, LOGLIK, QUESTION_BUDGET, TRAITS } from "../lib/solver.ts";

const hex = (bytes: number[]) => bytes.map((b) => b.toString(16).padStart(2, "0")).join("");

const digits = JOBS.flatMap((job) => [...job.p].map(Number)); // JOBS × TRAITS bytes, row-major
const codes = JOBS.flatMap((job) => [job.code >> 8, job.code & 0xff]); // uint16 big-endian
// int16 big-endian two's complement, indexed [answer * 10 + digit]
const loglik = LOGLIK.flatMap((row) => row.flatMap((v) => [((v & 0xffff) >> 8) & 0xff, v & 0xff]));

// Hash of the raw file bytes, so anyone can check it with any keccak tool against web/lib/matrix.json.
const matrixHash = keccak256(toBytes(readFileSync(new URL("../lib/matrix.json", import.meta.url))));

const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// GENERATED by web/scripts/gen-matrix-sol.ts from web/lib/matrix.json. Do not edit by hand.
// matrix.json keccak256: ${matrixHash}

/// @notice The Seer's job x trait matrix and answer log-likelihood table, embedded as code so the vault can check
///         whether a revealed job is consistent with the published transcript.
library SeerMatrix {
    uint256 internal constant JOBS = ${JOBS.length};
    uint256 internal constant TRAITS = ${TRAITS.length};
    uint256 internal constant QUESTIONS = ${QUESTION_BUDGET};
    int256 internal constant FIT_FULL = ${FIT_FULL};
    int256 internal constant FIT_FORFEIT = ${FIT_FORFEIT};
    bytes32 internal constant MATRIX_HASH = ${matrixHash};

    /// One byte per (job, trait): probability digit 0..9.
    bytes internal constant DIGITS = hex"${hex(digits)}";
    /// uint16 big-endian job code per row.
    bytes internal constant CODES = hex"${hex(codes)}";
    /// int16 big-endian round(1000 * ln P(answer | digit)), indexed [answer * 10 + digit].
    bytes internal constant LOGLIK = hex"${hex(loglik)}";

    function rowOf(uint16 code) internal pure returns (bool found, uint256 row) {
        bytes memory codes = CODES;
        for (uint256 j = 0; j < JOBS; j++) {
            if ((uint16(uint8(codes[2 * j])) << 8) | uint16(uint8(codes[2 * j + 1])) == code) return (true, j);
        }
        return (false, 0);
    }

    function logLik(bytes memory table, uint256 answer, uint256 digit) internal pure returns (int256) {
        uint256 i = 2 * (answer * 10 + digit);
        return int256(int16((uint16(uint8(table[i])) << 8) | uint16(uint8(table[i + 1]))));
    }
}
`;

writeFileSync(new URL("../../contracts/src/SeerMatrix.sol", import.meta.url), sol);
console.log(`wrote contracts/src/SeerMatrix.sol (${JOBS.length} jobs x ${TRAITS.length} traits), matrix hash ${matrixHash}`);
